### ISSUE TITLE
中文API文档”简化方式2“似乎有错

### ISSUE THREAD

**Issue by Jin-W-FS** [armink/EasyLogger#10]
https://github.com/armink/EasyLogger/blob/master/docs/zh/api/kernel.md#131-%E8%BE%93%E5%87%BA%E5%9F%BA%E6%9C%AC%E6%97%A5%E5%BF%97

1.3.1 输出基本日志

#define elog_assert(tag, ...) 
#define elog_a(tag, ...) //简化方式1，每次需填写 LOG_TAG
#define log_a(...)       //简化方式2，LOG_TAG 已经在文件顶部定义，使用前无需填写 LOG_TAG

#define elog_error(tag, ...)
#define elog_e(tag, ...)
#define log_a(...)

...
后面几项的log_a(...)似乎应该是log_e, log_w ...

**Comment by armink** [comment]
确实是，多谢反馈哈~

**Comment by armink** [comment]
已经 fix 了，你可以刷新下
