### ISSUE TITLE
此处存在溢出风险

### ISSUE THREAD

**Issue by Jin-W-FS** [armink/EasyLogger#12]
https://github.com/armink/EasyLogger/blob/7914a8e8350796351260067b16a69d294f93cb0f/easylogger/src/elog.c#L513

用gcc -O2 编译，在这一行报
> warning: call to __builtin___memcpy_chk will always overflow destination buffer

分析：
与elog_strcpy不同，strcpy函数会拷贝ELOG_NEWLINE_SIGN结束的'\0'字符，因此仅仅从log_buf的结尾退回newline_len = strlen(ELOG_NEWLINE_SIGN)个字节是不够的，得多退一个字节，修改成：
```strcpy(log_buf + ELOG_LINE_BUF_SIZE - newline_len - 1, ELOG_NEWLINE_SIGN);```

没有细看前后文，上文的log_len是否也应该减1？

**Comment by armink** [comment]
已使用 elog_strcpy 修复
