### ISSUE TITLE
缓冲区复用，需要清空

### ISSUE THREAD

**Issue by zxlcctv** [armink/EasyLogger#14]
https://github.com/armink/EasyLogger/blob/7914a8e8350796351260067b16a69d294f93cb0f/easylogger/src/elog.c#L396

log_buf每次用时，上次的数据还残留在缓冲区中，如果本次打印信息比上次短，上次的末尾也会打印出来。需要增加数据清空。

**Comment by armink** [comment]
https://github.com/armink/EasyLogger/blob/7914a8e8350796351260067b16a69d294f93cb0f/demo/os/linux/easylogger/port/elog_port.c#L58

日志的输出要用到长度，你也是这样用的吗？

**Comment by zxlcctv** [comment]
我用的是fprintf，没有用到size

**Comment by armink** [comment]
跟 `printf("%.*s", size, log);` 表达式一样的。你可以试试
