### ISSUE TITLE
EasyLogger和FlashDB一起使用时重新定义问题

### ISSUE THREAD

**Issue by 971586331** [armink/EasyLogger#150]
我在项目中同时用了EasyLogger和FlashDB，然后我发现log_e，log_i，log_d被重新定义了，不按设置的格式打印了，怎么解决呢
![image](https://github.com/armink/EasyLogger/assets/28640479/422d1e97-5ede-449b-a0c0-405849470e75)

**Comment by armink** [comment]
FlashDB 应该没有 log_x 的宏吧？

**Comment by armink** [comment]
这确实是一个问题，或者改下 fal_def.h 检测到 elog 就不用用这些宏？

**Comment by 971586331** [comment]
我把fal_def.h中的重新定义都注释了，然后在fal_def.h中包含elog.h就可以了
