### ISSUE TITLE
初始化有几率不成功导致无法正常使用

### ISSUE THREAD

**Issue by choujayyl** [armink/EasyLogger#16]
linux系统下，有几率初始化不成功什么原因，10次有两三次。不成功导致日志完全不能输出。
初始化不是同步执行吗？

**Comment by armink** [comment]
会不会是你的初始化晚于日志的输出。用自带的 linux demo 测试了吗？

**Comment by choujayyl** [comment]
发现在ide debug情况下，才会出现

**Comment by choujayyl** [comment]
关闭异步输出与缓存就好了。具体原因有时间再研究。
