### ISSUE TITLE
easylogger多线程模式下的堆栈资源优化建议

### ISSUE THREAD

**Issue by zlr3538** [armink/EasyLogger#2]
现在的easylogger虽然支持多线程，但是只是使用了一个信号量的保护，在资源占用上还有需要优化的地方。
主要是e_log宏虽然可以扩散到不同的task中，但是最终都是指向elog_output，从调用到最后输出都会在这个函数里面完成，这个函数占用很大的堆栈资源，而且随着每个task都使用e_log输出日志，每个task都要重复的占用这样的一个堆栈的资源。
比较好的一个方案是利用宏分开OS模式和BAREMETAL模式，当OS模式的时候，使用一个queue来存储每一个要发送的log，建立一个task从queue取出log并统一处理所有的输出，可以对queue的长度限制来限定资源。

**Comment by armink** [comment]
是的，EasyLogger 需要一个 **非阻塞日志输出模式** 。正好最近给 EasyLogger 设计 **文件存储插件**，到时候把这个模式一起加上。

**Comment by armink** [comment]
对了，你有没有日志的文件存储需求，有的话，可以看下这个 **[日志插件设计文档](http://naotu.baidu.com/file/c6eb0abaf872b6b8882d3f8332ba1920?token=03b61b231a28727e)** ，谈谈你需求和建议。

**Comment by armink** [comment]
@zlr3538 最近新增了日志 **异步输出日志** 日志模式，用户线程可以无需等待日志彻底输出完，即可直接返回。你可以使用 https://github.com/armink/EasyLogger/tree/master/demo/os/linux 这里的 Linux Demo 来试用下。更多配置及使用，详见说明文档。
