### ISSUE TITLE
存在数组越界

### ISSUE THREAD

**Issue by xzm7358** [armink/EasyLogger#21]
#ifdef ELOG_COLOR_ENABLE
    /* add CSI end sign */
    if (elog.text_color_enabled) {
        log_len += elog_strcpy(log_len, log_buf + log_len + fmt_result, CSI_END);
    }
#endif

log_buf + log_len + fmt_result可能超过ELOG_LINE_BUF_SIZE，导致数组越界

**Comment by armink** [comment]
刚刚做了些修正，你再看下吧
