### ISSUE TITLE
elog_flash_set_filter函数在头文件中给出,却没有实现

### ISSUE THREAD

**Issue by mysterywolf** [armink/EasyLogger#22]
elog_flash_set_filter在elog_flash.h头文件中给出定义,却没有在任何.c中实现,且源码中也不具备对从flash中抓出的日志进行过滤的功能,请问日后准备实现该功能吗?
                                                                                                       thanks and respect

**Comment by armink** [comment]
这个功能目前是没有的。主要现在好像没有这个需求呢。如果需要话，可以参考下面两个 api 封装下，就能用
```c
int8_t elog_find_lvl(const char *log);
const char *elog_find_tag(const char *log, uint8_t lvl, size_t *tag_len);
```

**Comment by armink** [comment]
还有其他问题吗？

**Comment by mysterywolf** [comment]
您好 谢谢您的回复 已经没有问题了 可以close了
