### ISSUE TITLE
怎么才能编译呢？

### ISSUE THREAD

**Issue by q962** [armink/EasyLogger#23]
一定要包含 rtthread.h 吗？

介绍里不是说`支持多种操作系统（RT-Thread、UCOS、Linux、Windows...），也支持裸机平台`
所以呢？？Linux、Windows 该如何编译呢？

**Comment by armink** [comment]
demos 文件夹下有各个系统的演示，你可以参考下

**Comment by q962** [comment]
尴尬，我现在才知道 rtt 是啥了，我下载错了
