### ISSUE TITLE
禁止输出时编译错误

### ISSUE THREAD

**Issue by mojinpan** [armink/EasyLogger#46]
在elog.h中elog_a~elog_v的宏定义默认给出了有效定义（187-192行），导致未定义ELOG_OUTPUT_ENABLE时不能将宏有效置空。

**Comment by armink** [comment]
刚修正了，你再试试，多谢反馈哈~

**Comment by mojinpan** [comment]
应该是把elog.h中elog_a~elog_v的宏定义默认给出了有效定义（187-192行），移至78行#else /* ELOG_OUTPUT_ENABLE */的后面：如下：
……
#ifndef ELOG_OUTPUT_ENABLE
    #define elog_a(tag, ...)
    #define elog_e(tag, ...)
    #define elog_w(tag, ...)
    #define elog_i(tag, ...)
    #define elog_d(tag, ...)
    #define elog_v(tag, ...)
#else /* ELOG_OUTPUT_ENABLE */
#define elog_a(tag, ...)     elog_assert(tag, __VA_ARGS__)
#define elog_e(tag, ...)     elog_error(tag, __VA_ARGS__)
#define elog_w(tag, ...)     elog_warn(tag, __VA_ARGS__)
#define elog_i(tag, ...)     elog_info(tag, __VA_ARGS__)
#define elog_d(tag, ...)     elog_debug(tag, __VA_ARGS__)
#define elog_v(tag, ...)     elog_verbose(tag, __VA_ARGS__)
……

**Comment by armink** [comment]
都行的，之前这个位置的定义写错了，所以修正下就行了

https://github.com/armink/EasyLogger/blob/fa7f940e0dab6d122234af8ae9e26df2371ba31c/easylogger/inc/elog.h#L71-L78

**Comment by mojinpan** [comment]
实际上是不行的，原文结构如下；
```
……
#ifndef ELOG_OUTPUT_ENABLE
    #define elog_a(tag, ...)
    #define elog_e(tag, ...)
    #define elog_w(tag, ...)
    #define elog_i(tag, ...)
    #define elog_d(tag, ...)
    #define elog_v(tag, ...)
#else /* ELOG_OUTPUT_ENABLE */
……
#endif /* ELOG_OUTPUT_ENABLE */
……
#define elog_a(tag, ...)     elog_assert(tag, __VA_ARGS__)
#define elog_e(tag, ...)     elog_error(tag, __VA_ARGS__)
#define elog_w(tag, ...)     elog_warn(tag, __VA_ARGS__)
#define elog_i(tag, ...)     elog_info(tag, __VA_ARGS__)
#define elog_d(tag, ...)     elog_debug(tag, __VA_ARGS__)
#define elog_v(tag, ...)     elog_verbose(tag, __VA_ARGS__)
……
```

无论#ifndef ELOG_OUTPUT_ENABLE 是否生效，最后面的elog_a~elog_v的定义均生效，导致错误，这部分内容必须放到：
```
#else /* ELOG_OUTPUT_ENABLE */
……
#endif /* ELOG_OUTPUT_ENABLE */
```

**Comment by armink** [comment]
你可以更新下来试试嘛，我这边测试没问题

改动位于：https://github.com/armink/EasyLogger/commit/6734e930fd9e56827e5c0cd13e6252dee0963d12
