### ISSUE TITLE
easylooger使用过程中遇到的问题，读写flash起始地址不一致。

### ISSUE THREAD

**Issue by heisewangluo** [armink/EasyLogger#5]
问题描述：每次读取日志的时候，开头4个字节是FF。
经过检查发现：假设日志地址：0x08033000
读日志时，读取的地址是从0x08033000开始读去的。但是写日志的时候，却是从0x08033004地址开始写的。所以，每次查看日志的适合前4个字节内容为FF;
请问我是不是哪里设置有问题？
EasyFlash设置flash地址200KB开始，开启了 环境变量、掉电保护。
EasyLogger设置基本没改动。
使用的是您项目里面的RTT演示部源码，但是看你介绍的动画图又没有这个情况。。。

**Comment by armink** [comment]
确实有这个问题，只不过我的用的两个终端软件 SecureCRT 和 Xshell 都不会显示 `0xFF` 对应的字符，所以一直也没有留意到。

**Comment by heisewangluo** [comment]
我这边是在`ubuntu`下开发的，使用`minicom`串口工具，碰巧这个工具把`0xFF`以`????`显示了出来。

**Comment by armink** [comment]
已经修复了，在这里： armink/EasyFlash@bc22795eeb3eddf5f43a2166e4fa1ee3c64d0abb 。

同时在 EasyLogger 的 RT-Thread Demo 中也做了同步更新，你再试试吧~

**Comment by heisewangluo** [comment]
OK! 没问题了。
