### ISSUE TITLE
elog_hexdump数据偏移地址问题

### ISSUE THREAD

**Issue by kingjason2009** [armink/EasyLogger#50]
感觉elog_hexdump函数打印的数据偏移好像有点问题：
fmt_result = snprintf(log_buf, ELOG_LINE_BUF_SIZE, "D/HEX %s: %04X-%04X: ", name, i, i + width);
是不是应该改为:
fmt_result = snprintf(log_buf, ELOG_LINE_BUF_SIZE, "D/HEX %s: %04X-%04X: ", name, i, i + width - 1);

**Comment by armink** [comment]
方便贴一下效果吗

**Comment by kingjason2009** [comment]
修改前hexdump效果：
![图片](https://user-images.githubusercontent.com/11486676/62409000-93a91680-b603-11e9-87fe-66501ace4704.png)
修改后效果：
![图片](https://user-images.githubusercontent.com/11486676/62409022-d4089480-b603-11e9-9056-08012e697b80.png)

**Comment by armink** [comment]
看起来确实是个显示错误，期待提个 pr 修正下哈

**Comment by Sunshine-du** [comment]
您好，请问elog_hexdump函数打印可以设置带颜色吗

**Comment by Sunshine-du** [comment]
您好，请问elog_hexdump函数打印可以设置带颜色吗
