### ISSUE TITLE
在linux下可以设置日志文件大小吗？

### ISSUE THREAD

**Issue by MyNewFlint** [armink/EasyLogger#52]
#define ELOG_FILE_MAX_SIZE  (10 * 1024) 这句话表示日志文件大小是10KB吗？

**Comment by armink** [comment]
对的，可又在 elog_cfg.h 中配置

**Comment by MyNewFlint** [comment]
你好，我现在想把日志文件大小设置成10kBytes，但是在实际的板子上运行发现日志文件大小超过10kBytes了

**Comment by armink** [comment]
为了保证行日志的完整性，好像最后一条日志会超出一丁点。这块你的使用受影响吗

**Comment by MyNewFlint** [comment]
我实际测试下来，不知道为啥会500kbytes，而且还在增加。对了这个日志可以设置成覆盖写吗？

**Comment by armink** [comment]
你是直接跑的 linux 下的那个 demo 吗？可以先什么都不改直接跑跑试试，默认是覆盖循环写的模式

**Comment by MyNewFlint** [comment]
我是在demo的基础上改了一下，那我先测试demo的，非常感谢

**Comment by MyNewFlint** [comment]
你好，我用demo重新编译运行了，没有问题。同时我又改了一下，现在可以了。应该是我第一次修改没有生效。目前我设置日志文件大小30kbytes，日志文件50个，测试下来是可以的，非常好，我再多跑一段时间试试

**Comment by armink** [comment]
好的，那 issue 先关闭了，以后有问题再打开
