### ISSUE TITLE
异步输出的时候，是否log不能在中断中使用？

### ISSUE THREAD

**Issue by siberianfox** [armink/EasyLogger#67]
因为我看到输出时候，会调用 **elog_output_lock();**
如果该函数是使用信号量来加锁解锁，那在中断中去获取锁就有可能导致死锁，我的理解对吗?

**Comment by armink** [comment]
不支持在中断中调用日志 API 哈

**Comment by siberianfox** [comment]
> 不支持在中断中调用日志 API 哈

非常感谢！: )
