### ISSUE TITLE
退出easylog机制

### ISSUE THREAD

**Issue by dubw** [armink/EasyLogger#72]
最近使用内存检测工具对代码进行检查时候，发现easylog并没有退出函数，导致跑完测试程序后，总是报多个malloc未释放

**Comment by armink** [comment]
是的，这块后面是得要加个 elog_deinit 接口

方便提交个 PR 实现下吗

**Comment by ZakiLiu** [comment]
> 最近使用内存检测工具对代码进行检查时候，发现easylog并没有退出函数，导致跑完测试程序后，总是报多个malloc未释放

是怎么对代码进行内存溢出检测的呢？

**Comment by dubw** [comment]
bb20ae32f63b220bf94a90935dc938cd488ff4ec  fix
