### ISSUE TITLE
elog_flash_flush()并没有输出缓冲区中的全部日志

### ISSUE THREAD

**Issue by z14git** [armink/EasyLogger#9]
我是这样发现的，按下某一按键后执行
```
{log_a(xxx);    elog_flash_flush();}
```
然后按下另一按键执行
```
elog_flash_output_recent(300);
```
结果发现最后一次log_a的信息没有输出。
通过仿真，发现elog_async.c中定义的log_buf[]里是存在最后一次log_a的信息的，但flash上却没有。
图中：红框部分是最后一次log_a信息的结尾，绿框是上一次log_a信息的结尾。
![elog_flash_flush_bug](https://user-images.githubusercontent.com/31793423/30357534-b6e797ea-9871-11e7-9660-d82680b7574d.jpg)

**ps:** elog_cfg.h中定义了**ELOG_ASYNC_OUTPUT_ENABLE**、**ELOG_ASYNC_LINE_OUTPUT**

**Comment by armink** [comment]
有没有在断言时候，把 elog_async, elog_output_lock, elog_flash_lock 这 3 个所取消？不取消的话断言里面日志代码就死锁了。
```
static void elog_user_assert_hook(const char* ex, const char* func, size_t line) {
    rt_enter_critical();
    elog_async_enabled(false);
    elog_output_lock_enabled(false);
    elog_flash_lock_enabled(false);
    elog_a("elog", "(%s) has assert failed at %s:%ld.\n", ex, func, line);
    cm_backtrace_assert(cmb_get_sp());
    elog_flash_flush();
    while(1);
}

void main(void)
{
    ......
    /* set EasyLogger assert hook */
    elog_assert_set_hook(elog_user_assert_hook);
    ......
}
```

**Comment by z14git** [comment]
抱歉，应该是我的使用方法有问题。  
由于在我的程序里面，执行按键功能的任务的优先级比异步输出的高，导致在按键功能里执行elog_flash_flush()时，elog_async.c中的log_buf[]虽然更新了，但elog_flash.c中的log_buf[]还没更新。

**Comment by armink** [comment]
好，有啥问题欢迎再继续讨论~
